apiVersion: apps/v1
kind: Deployment
metadata:
  name: todobackendservice
  labels:
    app: todobackendservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackendservice
  template:
    metadata:
      labels:
        app: todobackendservice
    spec:
      containers:
      - name: todobackendservice
        image: novatec/simpleweb:backend-tj-141119
        ports:
        - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: todobackendservice
  labels:
    app: todobackendservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: todobackendservice
    targetPort: 8090
  selector:
    app: todobackendservice
